### ISSUE TITLE
چجور میشه اسم فایلو عوض کرد؟

### ISSUE THREAD

**Issue by ehsansayrafi** [Keivan-sf/rjdl#1]

**Comment by Keivan-sf** [comment]
معذرت میخوام دیر میبینم. این کد فقط لینک دانلود رو میده به دولوپر که هر کاری لازمه باهاش بکنه. بیشتر برای  هدف استریم  آهنگ تو دیسکورد ساخته شده. میتونید بعد از گرفتن لینک با برنامه دانلودش کنید و اسم دلخواهنتونو بهش بدید

**Comment by ehsansayrafi** [comment]
ممنونم
